[package]
name = "rhytry"
version = "0.1.0"
publish = false
authors = ["misut <pkr5207@gmail.com>"]
edition = "2024"
exclude = ["assets", "build", "dist"]

[dependencies]
bevy = { version = "0.16.1", features = [
    "bevy_asset",
] }
bevy_asset_loader = "0.23.0"
