[tasks.check]
run = "cargo check"

[tasks.deploy]
depends = ["check"]
run = "gh workflow run deploy-github-page"

[tasks."fmt:cargo"]
description = "Format codes using cargo fmt"
run = "cargo +nightly fmt"

[tasks."fmt:mise"]
description = "Format codes using mise fmt"
run = "mise fmt"

[tasks.fmt]
depends = ["fmt:*"]
description = "Format codes using cargo and mise"

[tools]
"cargo:trunk" = "latest"
rust = "latest"
