# Trunk configuration
# For full list of options, see:
# https://trunkrs.dev/configuration/

[build]
## TO-BE-ENABLED-IN-RELEASE ## public_url = "/rhytry"
## TO-BE-ENABLED-IN-RELEASE ## release = true
no_sri = true
